name: Deploy Terraform state to backend

on:
  workflow_dispatch:

jobs:
  Deploy:
    name: 'Deploy TF State to backend'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Deploy TF State
        run: |
          set -a
          source .env.backend

          az group create \
            -l $TF_VAR_location \
            -n $TF_VAR_resource_group_name

          az storage account create \
            -n $TF_VAR_state_storage_account_name \
            -g $TF_VAR_resource_group_name \
            -l $TF_VAR_location \
            --sku Standard_LRS \
            --allow-blob-public-access false

          az storage container create \
            --name tfstate \
            --account-name $TF_VAR_state_storage_account_name
