name: Deploy Terraform state to backend
'on':
  workflow_dispatch:
jobs:
  Deploy:
    name: Deploy TF State to backend
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
      - name: Deploy TF State
        run: |
          set -a
          source .env.backend
          az login --service-principal \
            -u ${{ secrets.CLIENT_ID }} \
            -p ${{ secrets.CLIENT_SECRET }} \
            --tenant ${{ secrets.TENANT_ID }}

          az keyvault create \
            -n $TF_VAR_state_key_vault_name \
            -l $TF_VAR_location \
            -rg $TF_VAR_state_resource_group_name