name: Deploy Terraform state to backend

'on':
  workflow_dispatch:

jobs:
  Deploy:
    name: Deploy TF State to backend
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Deploy TF State
        run: |
          set -a
          source .env.backend
          az login --service-principal \
            -u ${{ secrets.CLIENT_ID }} \
            -p ${{ secrets.CLIENT_SECRET }} \
            --tenant ${{ secrets.TENANT_ID }}

          az group create \
            -l $TF_VAR_location \
            -n $TF_VAR_state_resource_group_name

          az storage account create \
            -n $TF_VAR_state_storage_account_name \
            -g $TF_VAR_state_resource_group_name \
            -l $TF_VAR_location \
            --sku Standard_LRS \
            --allow-blob-public-access false

          az storage container create \
            --name $TF_VAR_state_storage_account_container_name \
            --account-name $TF_VAR_state_storage_account_name

          az keyvault create \
            -n $TF_VAR_state_key_vault_name \
            -l $TF_VAR_location \
            -g $TF_VAR_state_resource_group_name

          ssh-keygen -t rsa -b 4096 -f tfazlnxkey -N ""

      - name: Upload SSH public key to Key Vault
        run: |
          az keyvault secret set \
            --vault-name ${{ env.TF_VAR_state_key_vault_name }} \
            --name tfazlnxkeypub \
            --file tfazlnxkey.pub

      - name: Upload SSH private key to Key Vault
        run: |
          az keyvault secret set \
            --vault-name ${{ env.TF_VAR_state_key_vault_name }} \
            --name tfazlnxkeypriv \
            --file tfazlnxkey
