name: Deploy Terraform on Release

on:
  push:
    branches: 
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Load environment variables from .env.backend
        run: |
          cat .env.backend | grep -v '^#' | while IFS= read -r line; do
            echo "$line" >> $GITHUB_ENV
          done

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.11

      - name: Configure Azure credentials
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -input=false tfplan
