on:
  release:
    types:
      - published
    branches:
      - main

name: On release Main 

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
        
    steps:
        - name: Checkout
          uses: actions/checkout@v4.1.6

        - name: Login to Azure
          run: |
            az login --service-principal \
              -u ${{ secrets.CLIENT_ID }} \
              -p ${{ secrets.CLIENT_SECRET }} \
              --tenant ${{ secrets.TENANT_ID }}

        - name: Install Terraform
          uses: hashicorp/setup-terraform@v3.1.1
          with:
            terraform_version: ${{ env.TF_VERSION }}
        
        - name: Terraform init
          id: init
          run: | 
            set -a 
            source ../.env.backend
            terraform init \
            -backend-config="resource_group_name=$TF_VAR_state_resource_group_name" \
            -backend-config="storage_account_name=$TF_VAR_storage_account_name"
        
        - name: Terraform fmt
          id: fmt
          run: terraform fmt -check

        - name: Terraform validate
          id: validate
          run: terraform validate -no-color

        - name: Terraform plan
          id: plan
          run: terraform plan -no-color
  
        - name: Terraform apply
          id: apply
          run: terraform apply -auto-approve